### ISSUE TITLE
Wrong Shader Version on Linux

### ISSUE THREAD

**Issue by qtux** [KTXSoftware/krafix#2]
Executing a program using the generated glsl shaders fails with the following error.

```
GLSL compiler error: 0:4(1): error: no precision specified this scope for type `vec2'
GLSL linker error: error: linking with uncompiled shader
```

A quick solution is to change `#version 100` e.g. to `#version 110` in both shaders.

**Comment by RobDangerous** [comment]
Thanks. What glsl versions are accepted depends on a lot of factors, especially on Linux, but 110 seems to be the safest bet.
