### ISSUE TITLE
agal OpAccessChain wrong result

### ISSUE THREAD

**Issue by juakob** [KTXSoftware/krafix#35]
If you try to translate this fragment:
        vec4 c1 = texture2D( tex, texCoord);
    vec4 finalColor=vec4( c1.x, c1.y, c1.z, c1.w);
    gl_FragColor = finalColor;

you get this agal code:

mov ft0, v0
tex ft0, ft0, fs0 <2d, wrap, linear>
mov ft0, ft0
**_mov ft1, ft0.w_**
mov ft1, ft1
**_mov ft2, ft0.w_**
mov ft2, ft2
**_mov ft3, ft0.w_**
mov ft3, ft3
**_mov ft0, ft0.w_**
mov ft0, ft0
mov ft1.x, ft1.x
mov ft1.y, ft2.y
mov ft1.z, ft3.z
mov ft1.w, ft0.w
mov ft0, ft1
mov ft0, ft0
mov oc, ft0

clearly the output shoul write  **_mov ft1, ft0.x_** **_mov ft2, ft0.y_** etc, instead.

I found that the op that generates thoues lines is OpAccessChain
In my test the problem is that indexName expects a number between 0 and 3, and if its bigger than 3 it just returns "w".
I made the code work by changing indexName to

const char\* indexName(unsigned index) {
        switch (index) {
        case 0:
            return "x";
        case 1:
            return "y";
        case 2:
            return "z";
        case 22:
            return "x";
        case 26:
            return "y";
        case 29:
            return "z";
        case 3:
        default:
            return "w";
        }
    }
I cant figure out why inst.operands[3] has those values. In another example I have other values like 58,61,64,67. 

Any help would be greate! thanks

**Comment by juakob** [comment]
A quick solution is to just eliminate the code that handles the slot index, after all the code generated dosent use the rest of the slots, so mov ft1, ft0.w is the same as mov ft1, ft0. I tested this hack in two less trivial shader and the result was correct, but dont know if there is a case were the generated code uses the other slots of the register to save other stuff.

**Comment by RobDangerous** [comment]
Problem was that the parameters are not the indices themselves but the ids of values containing the indices. SPIR-V operations are described at https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html btw.

**Comment by juakob** [comment]
Awesome!
