### ISSUE TITLE
HLSL/D3D11 maximum constant size

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#43]
Constant size/offset is capped to one byte. This prevents setting bigger arrays exceeding the size of 255.

In Kore constant.offset and constant.size are also defined as u8:
https://github.com/Kode/Kore/blob/master/Backends/Graphics4/Direct3D11/Sources/Kore/ShaderImpl.cpp#L46

**Comment by RobDangerous** [comment]
Fixed.
