### ISSUE TITLE
HLSL missing functions

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#44]
- Declaring `uniform samplerCube shadowMapCube;` throws at compile-time:
`error X3000: unrecognized identifier 'samplerCube'`

- Using `textureLod()` throws at compile-time:
`error X3004: undeclared identifier 'tex2DLod'`

**Comment by RobDangerous** [comment]
textureLod is fixed in KhronosGroup/SPIRV-Cross#161

**Comment by RobDangerous** [comment]
Cube maps now have also been fixed in the same pull-request.

**Comment by RobDangerous** [comment]
Fixed in the latest krafix binary.
