### ISSUE TITLE
GL_NV_geometry_shader_passthrough extension

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#48]
glslang does not expose vender specific opengl extensions by default, preventing to access them from krafix.

This could be solved by adding into the `korefile.js`:
```
project.addDefine('NV_EXTENSIONS');
project.addDefine('AMD_EXTENSIONS');
```

I tested with NV_EXTENSIONS, and the resulting binary raised about 50KB in size. Could we enable this by default? Any ideas on more solutions?

Related:
https://github.com/KhronosGroup/glslang/blob/master/CMakeLists.txt#L34

**Comment by luboslenco** [comment]
Related: https://github.com/KhronosGroup/SPIRV-Cross/issues/379.

**Comment by RobDangerous** [comment]
Oh, ping me if I fail to answer an easy question in time. My vote goes for activating both by default.

**Comment by luboslenco** [comment]
Sounds good! Created a PR, however not much use for it yet till spirv-cross adds support for those I guess.

**Comment by luboslenco** [comment]
https://github.com/Kode/krafix/pull/52 now merged, just waiting for the `GL_NV_geometry_shader_passthrough` extension support in spirv-cross.

**Comment by luboslenco** [comment]
Closing in favor of https://github.com/KhronosGroup/SPIRV-Cross/issues/379.
