### ISSUE TITLE
transpose for glsl110/Linux

### ISSUE THREAD

**Issue by RobDangerous** [KTXSoftware/krafix#50]
transpose requires glsl120, but we set 110 on Linux because we had error reports for some 3XX version and 110 seemed like the safest bet, so let's emit a transpose implementation for Linux.

**Comment by RobDangerous** [comment]
Might also make sense for iOS, see https://stackoverflow.com/questions/18034677/transpose-a-mat4-in-opengl-es-2-0-glsl

**Comment by luboslenco** [comment]
I think we even had this back when krafix did it all. 😃 On Linux I am now manually doing `--shaderversion 330` (for voxel stuff) and seems to also work fine so far.

**Comment by RobDangerous** [comment]
I think there were two persons in my lectures who couldn't run 330 on their Linux machines. No idea if there are any statistics out there, probably not.

**Comment by hamaluik** [comment]
Just ran headfirst into this issue. Any updates on it?

**Comment by RobDangerous** [comment]
I discussed it with Captain Obvious right this moment and he told me there's no updates on this.
