### ISSUE TITLE
Setting float/int precision

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#51]
Trying to set precision, which is useful for gles targets:

```glsl
#version 450
in vec3 test;
out vec4 FragColor;
void main() {
	mediump vec3 v = test * vec3(0.5);
	FragColor = vec4(v.xyz, 1.0);
}
```

Results in `mediump` being discarded:

```glsl
#version 100
precision mediump float;
precision highp int;

varying highp vec3 test;

void main()
{
    highp vec3 v = test * vec3(0.5);
    gl_FragData[0] = vec4(v, 1.0);
}
```

Possible solution hinted by Hans:
`I suspect you are compiling with GL semantics. mediump/highp does not mean anything in GLSL 4.5, and is probably just ignored. Tried using Vulkan GLSL? That should work.`

**Comment by luboslenco** [comment]
More testing (https://github.com/luboslenco/mediump_test) on the latest krafix, it's the `shader-webgl2.frag.essl` variant which is problematic, as it defaults to `mediump` for some reason. The regular webgl1 shader (pasted in original post) discards the `mediump` qualifier but defaults to `highp`, so less trouble there.

```glsl
#version 300 es
precision mediump float;
precision mediump int;

in vec3 test;
out vec4 FragColor;

void main()
{
    vec3 v = test * vec3(0.5);
    FragColor = vec4(v, 1.0);
}
```

Ideal solution: default to `highp` everywhere, honor setting `mediump` manually for performance.

**Comment by juakob** [comment]
I think is best to not set the precision, unless is specify. [specification](https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf)

> The vertex language requires any uses of lowp, mediump and highp to compile and link without error. The fragment language requires any uses of lowp and mediump to compile without error.  Support for highp is optional.

> The vertex language has the following predeclared globally scoped default precision statements:
precision highp float;
precision highp int;
precision lowp sampler2D;
precision lowp samplerCube;
The fragment language has the following predeclared globally scoped default precision statements:
precision mediump int;
precision lowp sampler2D;
precision lowp samplerCube;

**Comment by luboslenco** [comment]
As I understand Spirv-Cross already defaults to highp (unless you manually specify precision):
https://github.com/KhronosGroup/SPIRV-Cross/issues/401#issuecomment-357987374

It's our webgl2 variant which produces odd output, and that is based on GLES 3.0 where highp support should be mandatory.

For painter shaders we can still set the mediump precision to keep compatible with ancient hardware, but otherwise for 3D stuff you always end up with broken stuff on mobile.

**Comment by RobDangerous** [comment]
For webgl we already do compile three variants automatically because of the optional nature of highp support in fragment shaders so there's no need for special treatment of the painter shaders. The webgl2 non-highp output is really the only problem here I think and I have not yet figured out why that happens.

**Comment by RobDangerous** [comment]
Well, let's not talk about this ever again. Compiling new binaries for Mac and Linux tomorrow.
