### ISSUE TITLE
HLSL slow compile

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#61]
Example shader which triggers slow compiling:

```glsl
#version 450
uniform sampler2D gbufferD;
in vec3 viewRay;
out vec4 fragColor;
vec3 hitCoord;

float getDeltaDepth(vec3 hitCoord) {
	return texture(gbufferD, hitCoord.xy).r - hitCoord.z;
}

vec4 binarySearch(vec3 dir) {	
	for (int i = 0; i < 20; i++) {
		hitCoord -= dir;
		if (getDeltaDepth(hitCoord) < 0.0) hitCoord += dir;
	}
	return vec4(1.0);
}

vec4 rayCast(vec3 dir) {
	for (int i = 0; i < 20; i++) {
		hitCoord += dir;
		if (getDeltaDepth(hitCoord) > 0.0) return binarySearch(dir);
	}
	return vec4(0.0);
}

void main() {
	fragColor = rayCast(viewRay);
}
```

- 7 sec to compile , `.d3d11` size is 67KB (grows with the amount of loops)

```glsl
#version 450
uniform sampler2D gbufferD;
in vec3 viewRay;
out vec4 fragColor;
vec3 hitCoord;

float getDeltaDepth(vec3 hitCoord) {
	// return texture(gbufferD, hitCoord.xy).r - hitCoord.z;
	return hitCoord.x - hitCoord.z; // <--- HERE
}

vec4 binarySearch(vec3 dir) {	
	for (int i = 0; i < 20; i++) {
		hitCoord -= dir;
		if (getDeltaDepth(hitCoord) < 0.0) hitCoord += dir;
	}
	return vec4(1.0);
}

vec4 rayCast(vec3 dir) {
	for (int i = 0; i < 20; i++) {
		hitCoord += dir;
		if (getDeltaDepth(hitCoord) > 0.0) return binarySearch(dir);
	}
	return vec4(0.0);
}

void main() {
	fragColor = rayCast(viewRay);
}
```

- <1sec to compile, `.d3d11` size is 1KB

If this is related to loop unrolling, do we have a way to prevent that for fast debug builds?

**Comment by RobDangerous** [comment]
Some loop unrolling taking seven seconds isn't ok, we have to profile and fix that instead of making it optional.

**Comment by luboslenco** [comment]
I have also found out shader affected by this is ~3x slower compared to glsl (but still produces correct result). Did not dig further yet.

**Comment by luboslenco** [comment]
Fixed by replacing:
```glsl
texture(gbufferD, getProjectedCoord(hitCoord))
```

with:
```glsl
textureLod(gbufferD, getProjectedCoord(hitCoord), 0.0)
```

I guess with the former, compiler unrolled it even though it's perhaps not favorable in this case - due to
`Gradient-based operations must be moved out of flow control to prevent divergence.`

With the later, compilation is instant and it's as fast as the glsl variant.

Would be cool to have more control over this with `[loop]` `[unroll]` hints, but I guess that is not possible with glsl.
