### ISSUE TITLE
Add SPIRV-Tools Optimizer pass

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#63]
Perhaps as an optional flag when calling krafix.
https://github.com/KhronosGroup/SPIRV-Tools#optimizer

**Comment by RobDangerous** [comment]
It's in but it doesn't work :-( Not sure I want to go back to it, I want to get away from using other people's code for shader-things. But the lib is in, including commented-out code for running it for anyone who wants to have a closer look.

**Comment by RobDangerous** [comment]
Oh, looks like it's actually working for Vulkan now, just made a silly, little mistake.
