### ISSUE TITLE
Compiling compute shader to metal -> texture bindings have the same index

### ISSUE THREAD

**Issue by kirnuarp** [KTXSoftware/krafix#64]
for example
layout (binding = 0, rgba32f) uniform writeonly image2D destTex;
layout (binding = 1, rgba32f) uniform readonly image2D sourceTex;

becomes to

kernel void test_comp_main(texture2d<float, access::read> sourceTex [[texture(0)]], texture2d<float, access::write> destTex [[texture(0)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])

there are two texture(0)'s

**Comment by RobDangerous** [comment]
Fixed.
