### ISSUE TITLE
Unable to build Kha apps from a system with glibc 2.27

### ISSUE THREAD

**Issue by Sanva** [KTXSoftware/krafix#77]
Hi!

I'm not sure if this is desired/needed or something that went unnoticed, but appears that now Kha apps can't be build in Linux systems with a glibc version less than 2.29:

```
Compiling shader 1 of 8 (painter-colored.frag.glsl).
.../Kinc/Tools/krafix/krafix-linux64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by .../Kinc/Tools/krafix/krafix-linux64)
Compiling shader 1 of 8 (painter-colored.frag.glsl) failed:
Shader compiler error.
```

Looks to me that this can be the reason, since this was working to me until today → https://github.com/Kode/krafix/commit/7f8fced63382cfef47a60e4a1d21d8271766aa7d .

To be clear, I'm not saying this should be changed back nor anything like that — but I would appreciate some feedback to know if I should update my system or if this is really an unwanted dependency change that went unnoticed.

**Comment by RobDangerous** [comment]
That commit was done to fix this because GitHub switched to a later Ubuntu version automatically - as you can see, the commit changed it from latest to 18.04. But I had not changed the Kha/Kinc repos yet to point to the latest commits so you're probably still on the earlier version. Did that now.

**Comment by Sanva** [comment]
> as you can see, the commit changed it from latest to 18.04

Wow, yes, I totally changed that red/green colors in my mind or something :man_facepalming: — sorry for the noise and thanks a lot for the really quick update :smiling_face_with_three_hearts:
