### ISSUE TITLE
Vulkan textures broken

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#83]
It looks like after the https://github.com/Kode/krafix/commit/2ff05b4b4aa3cff7798e29ce6e6eaf91d545c30e only a black screen shows up when running https://github.com/Kinc-Samples/Texture-Kinc on Linux + Vulkan.

**Comment by RobDangerous** [comment]
There's much more broken, still working through the current set of validation layers to get to the root of things.

**Comment by RobDangerous** [comment]
Fixed.

**Comment by luboslenco** [comment]
Thanks!
