### ISSUE TITLE
gl_VertexID broken on Vulkan

### ISSUE THREAD

**Issue by luboslenco** [KTXSoftware/krafix#84]
Not sure if this is on purpose, using `gl_VertexID` worked at https://github.com/Kode/krafix/commit/ea222cde885484ad44e68d3ee0bd4cf288473985 but now it assets when calling `vkCreateGraphicsPipelines`.

**Comment by RobDangerous** [comment]
Hu, I cut that out because the validation layers told me vertexId isn't allowed.

**Comment by RobDangerous** [comment]
So, gl_VertexID is indeed not a thing in Vulkan but it looks like drivers are generous. Instead there's gl_VertexIndex - which apparently is similar but different in details I still have to find out about. I'll rewrite gl_VertexID to gl_VertexIndex for now.

**Comment by luboslenco** [comment]
Super cool!

**Comment by luboslenco** [comment]
On no, it looks like this re-introduced https://github.com/Kode/krafix/issues/83, ie. getting black screen for https://github.com/Kinc-Samples/Texture-Kinc.

**Comment by RobDangerous** [comment]
Reopening...

**Comment by RobDangerous** [comment]
Reclosing.
