### ISSUE TITLE
Vulkan error when trying to compile a pipeline using attached shader

### ISSUE THREAD

**Issue by tcdude** [KTXSoftware/krafix#90]
I get the following error when trying to compile a Vulkan pipeline using the shaders stored in this zip: [shader_pair.zip](https://github.com/Kode/krafix/files/9706455/shader_pair.zip)

```
Vulkan ERROR: Code 7060244 : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55555c32f920, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
  %104 = OpAccessChain %_ptr_UniformConstant_float %792 %uint_0
```

**Comment by RobDangerous** [comment]
Next problem is according to tizi:
```Structure id 792 decorated as Block for variable in Uniform storage class must follow standard uniform buffer layout rules: member 1 at offset 4 is not aligned to 8```
